name: Checks

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run format:check

  may-merge:
    needs: ["format"]
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
